### ISSUE TITLE
/history is broken

### ISSUE THREAD

**Issue by gjtokkel** [Endogen/Telegram-Kraken-Bot#16]
Hi,

I like your program a lot and am using it. It looks like in your last version (3-jan-2017) the /history has been broken.

Grz,

Joost

**Comment by gjtokkel** [comment]
more details:

2018-01-03 13:04:24,654 - DEBUG - telegram.bot - Exiting: send_message
2018-01-03 13:04:24,658 - DEBUG - root - history_cmd - args: [('method', 'TradesHistory'), ('data', None), ('private', True), ('return_error', True), ('retries', None)]
2018-01-03 13:04:28,009 - ERROR - telegram.ext.dispatcher - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/conversationhandler.py", line 295, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 171, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "telegram_kraken_bot.py", line 172, in _restrict_access
    return func(bot, update)
  File "telegram_kraken_bot.py", line 977, in history_cmd
    msg = get_trade_str(newest_trade) + " (Value: " + total_value + " EUR)"
  File "telegram_kraken_bot.py", line 929, in get_trade_str
    pair_str = pair_str[1:] if pair_str.startswith("X") else pair_str
**UnboundLocalError: local variable 'pair_str' referenced before assignment**

**Comment by Endogen** [comment]
Yep, looks like a bug :) Thanks for reporting! Will take a look today Abd fix it

**Comment by gjtokkel** [comment]
Tnx David.  No rush...

Op 3 jan. 2018 3:31 p.m. schreef David Strohmayer <notifications@github.com>:

Yep, looks like a bug :) Thanks for reporting! Will take a look today Abd fix it

**Comment by Endogen** [comment]
This wasn't actually easy to fix. Check out the latest version of the bot. It's fixed there.

Do you still know how to replicate it? It would be interesting to know for which value this exception occurred. It for sure occurred if the string didn't have any `Z` in it but that should never be the case...

If you know how to replicate it, please update to the latest version, replicate what you have done before (there will be no error now) and send me the logs. There should be an entry that starts like this:

```
2018-01-03 23:06:17,679 - WARNING - root - Can't replace 'Z' in <some_string> 
```

The <some_string> value would be interesting here.

**Comment by gjtokkel** [comment]
hi, done.  Indeed error is gone.

It was XLMXBT pair  :)    Something your script cannot trade....  Thats probably why you could not reproduce it...


The log:

...

2018-01-04 09:14:10,088 - DEBUG - telegram.bot - Exiting: send_message
2018-01-04 09:14:10,092 - WARNING - root - Can't replace 'Z' in 'XXLMXXBT'
2018-01-04 09:14:10,096 - DEBUG - telegram.bot - Entering: send_message
2018-01-04 09:14:10,147 - DEBUG - telegram.vendor.ptb_urllib3.urllib3.connectionpool - https://api.telegram.org:443 "POST /...

Tnx,


Joost

________________________________
Van: David Strohmayer <notifications@github.com>
Verzonden: woensdag 3 januari 2018 22:20:04
Aan: Endogen/Telegram-Kraken-Bot
CC: gjtokkel; Author
Onderwerp: Re: [Endogen/Telegram-Kraken-Bot] /history is broken (#16)


This wasn't actually easy to fix. Check out the latest version of the bot. It's fixed there.

Do you still know how to replicate it? It would be interesting to know for which value this exception occurred. It for sure occurred if the string didn't have any Z in it but that should never be the case...

If you know how to replicate it, please update to the latest version, replicate what you have done before (there will be no error now) and send me the logs. There should be an entry that starts like this:

2018-01-03 23:06:17,679 - WARNING - root - Can't replace 'Z' in <some_string>


The <some_string> value would be interesting here.

**Comment by Endogen** [comment]
Ok, thank you for the help! I will look into supporting other currencies (not only fiat currencies) in the config setting `trade_to_currency`

**Comment by gjtokkel** [comment]
Thanx David

Met vriendelijke groet,

Joost de Haan

________________________________
Van: David Strohmayer <notifications@github.com>
Verzonden: Thursday, January 4, 2018 9:23:28 AM
Aan: Endogen/Telegram-Kraken-Bot
CC: gjtokkel; Author
Onderwerp: Re: [Endogen/Telegram-Kraken-Bot] /history is broken (#16)


Ok, thank you for the help! I will look into supporting other currencies (not only fiat currencies) in the config setting trade_to_currency
