### ISSUE TITLE
BadRequest: Chat not found

### ISSUE THREAD

**Issue by tuerkasten** [Endogen/Telegram-Kraken-Bot#26]
As I start the bot, the prompt responds with:
ubuntu@tuerBuntu:~/telegram-kraken-bot/Telegram-Kraken-Bot$ python3.6 telegram_kraken_bot.py &
[1] 20982
ubuntu@tuerBuntu:~/telegram-kraken-bot/Telegram-Kraken-Bot$ 2018-09-08 16:47:47,556 - DEBUG - telegram.ext.dispatcher - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x75b314f0>
2018-09-08 16:47:47,565 - DEBUG - telegram.bot - Entering: send_message
2018-09-08 16:47:47,567 - DEBUG - telegram.vendor.ptb_urllib3.urllib3.connectionpool - Starting new HTTPS connection (1): api.telegram.org
2018-09-08 16:47:49,886 - DEBUG - telegram.vendor.ptb_urllib3.urllib3.connectionpool - https://api.telegram.org:443 "POST xxx/sendMessage HTTP/1.1" 400 73
Traceback (most recent call last):
  File "telegram_kraken_bot.py", line 2050, in <module>
    init_cmd(None, None)
  File "telegram_kraken_bot.py", line 1802, in init_cmd
    updater.bot.send_message(uid, msg, disable_notification=True, reply_markup=ReplyKeyboardRemove())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/telegram/bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/telegram/bot.py", line 85, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/telegram/utils/request.py", line 272, in post
    **urlopen_kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/telegram/utils/request.py", line 210, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Chat not found

[1]+  Exit 1                  python3.6 telegram_kraken_bot.py

and the bot doesn't start. I have created a bot on telegram and put my API Key's into the file. Did I miss anything else?

**Comment by tuerkasten** [comment]
had the wrong ID in config file. issue solved

**Comment by Endogen** [comment]
Happy to hear you resolved the issue 👍

**Comment by tuerkasten** [comment]
I really like the bot. This takes my trading to a whole new level! Is there any chance to include leveraged orders? Would really appreciate that feature!

Cheers
