### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by enea1982** [Endogen/Telegram-Kraken-Bot#27]
hello when I put python3 telegram_kraken_bot.py & to start the boto gives me this error

  File "telegram_kraken_bot.py", line 12, in <module>
     from enum import Enum, car
ImportError: can not import name 'auto'

**Comment by Endogen** [comment]
That's because you don't use Python 3.6 but most probably some earlier version. This is from the README:
___
Prerequisites

Python version

You have to use Python 3.6 to execute the script (because of enum method auto()). If you would like to use Python 3.4 or 3.5, you have to remove auto from imports and set the values in WorkflowEnum and KeyboardEnum yourself. Python 2.x is not supported.
___
if you want to check your Python version, open a terminal and enter `python3 --version`

**Comment by enea1982** [comment]
now I'm giving this error 
Traceback (most recent call last):
   File "telegram_kraken_bot.py", line 17, in <module>
     from telegram import KeyboardButton, ReplyKeyboardMarkup, ReplyKeyboardRemove, ParseMode
ModuleNotFoundError: No module named 'telegram'

**Comment by enea1982** [comment]
with Python 3.6

**Comment by enea1982** [comment]
sorry there is a fairy to install it on the pc goes but the smartphon of a friend of mine does not go as never ??

**Comment by enea1982** [comment]
how can I start the bot for users who want to do treding

**Comment by Endogen** [comment]
> now I'm giving this error
> Traceback (most recent call last):
> File "telegram_kraken_bot.py", line 17, in 
> from telegram import KeyboardButton, ReplyKeyboardMarkup, ReplyKeyboardRemove, ParseMode
> ModuleNotFoundError: No module named 'telegram'

you have to install the requirements. Please take a look at the [README](https://github.com/Endogen/Telegram-Kraken-Bot/blob/master/README.md#installing-needed-modules-from-requirementstxt)

> how can I start the bot for users who want to do treding

you have to start the bot on a PC [like this](https://github.com/Endogen/Telegram-Kraken-Bot/blob/master/README.md#starting)

**Comment by enea1982** [comment]
if I try with another cell phone of a friend of mine the bot does not work instead on the computer and on my cell phone the bot works for me
how can I make the way other users enter to invest in the bot?

**Comment by Endogen** [comment]
This is on purpose. Only one user (the one in the config) is allowed to use the bot. Out of security reasons. 

If you want another user to use this bot, then you have two options:
1. Set up your own Telegram account on the phone of your friend
2. Start another bot with the new user ID and new bot token in the config

There was already discussion in the past to allow multiple Telegram users to use one bot but i haven't implemented it yet. I plan to do it but it will take time so this is not coming soon.

**Comment by enea1982** [comment]
you will also collect referrals from the bot?

**Comment by Endogen** [comment]
No

**Comment by enea1982** [comment]
hi when i do deposit it tells me invalid api key how do you get the epi key?

**Comment by enea1982** [comment]
or done as the rules said, but tell me! ️ EAPI: Invalid key?

**Comment by enea1982** [comment]
‼️ EGeneral: Internal error

**Comment by enea1982** [comment]
or done as the rules said, but tell me! ️ ‼️ EGeneral: Internal error?

**Comment by enea1982** [comment]
or done as the rules said, but tell me! ️ EAPI: Invalid key?

**Comment by Endogen** [comment]
it means that the API keys are not correct. are you sure that you copied the keys correctly?

**Comment by enea1982** [comment]
sure I did copy and paste you can not go wrong

**Comment by Endogen** [comment]
Have you checked all the checkboxes?
![bildschirmfoto 2018-09-19 um 20 15 26](https://user-images.githubusercontent.com/226475/45772740-d7439d80-bc48-11e8-9cdf-40f956c77f27.png)

**Comment by enea1982** [comment]
a question when you do the job in the bot so that users can invest in the bot?

**Comment by enea1982** [comment]
no to register other users in the bot?

**Comment by enea1982** [comment]
this error [1] 2710
root@admin:~/Telegram-Kraken-Bot# Traceback (most recent call last):
  File "telegram_kraken_bot.py", line 82, in <module>
    updater = Updater(token=config["bot_token"])
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/updater.py", line 122, in __init__
    self.bot = Bot(token, base_url, request=self._request)
  File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 108, in __init__
    self.token = self._validate_token(token)
  File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 129, in _validate_token
    if any(x.isspace() for x in token):
TypeError: 'int' object is not iterable

**Comment by Endogen** [comment]
In the config file `config.json` there is this entry:
```
"bot_token" : "304028949:AAFXs8EbIkRw7oWkZ0O1t6vgMhWL3uQzUfo",
```
There you have to replace this value `304028949:AAFXs8EbIkRw7oWkZ0O1t6vgMhWL3uQzUfo` with your bot token. You get the bot token when you talk to user `@BotFather` on Telegram. See [this](https://core.telegram.org/bots#6-botfather)

The bot token value has to be in quotation marks

**Comment by enea1982** [comment]
hello sorry on deposit me from no wallet fund?

**Comment by Endogen** [comment]
sorry i don't understand...

**Comment by enea1982** [comment]
when I make a deposit the bot tells me No wallet found

**Comment by Endogen** [comment]
That's because you didn't generate a wallet on Kraken.com but that's what you have to do first. Anyway, i wouldn't use the bot for deposits and withdrawals. Better do that on the website and only trade with the bot.
