### ISSUE TITLE
get balance seems broken recently

### ISSUE THREAD

**Issue by tuerkasten** [Endogen/Telegram-Kraken-Bot#28]
not receiving my balance anymore. An uncaught error was raised while processing... this is the complete output:

2018-09-25 04:47:31,467 - ERROR - telegram.ext.dispatcher - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 171, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "telegram_kraken_bot.py", line 252, in _restrict_access
    return func(bot, update)
  File "telegram_kraken_bot.py", line 293, in balance_cmd
    available_value = float(available_value) - (float(order_volume) * float(price_per_coin))
ValueError: could not convert string to float: 'loss'

**Comment by tuerkasten** [comment]
I've closed a position for btc profit which shaked my account from 0 holdings to just a little bit more, but after that, the function worked fine again 💃

**Comment by Endogen** [comment]
👍  good to hear that. i guess it was some kind of Kraken fuckup 😄
